steps:
  - name: hashicorp/terraform:1.6.6
    id: terraform-init
    dir: infra
    entrypoint: sh
    args:
      - -c
      - |
        terraform init \
          -backend-config="bucket=${_TF_STATE_BUCKET}" \
          -backend-config="prefix=${_TF_STATE_PREFIX}"

  - name: gcr.io/cloud-builders/gcloud
    id: configure-docker
    args:
      - auth
      - configure-docker
      - "${_AR_REGION}-docker.pkg.dev"
      - --quiet

  - name: gcr.io/cloud-builders/docker
    id: copy-dbt-image
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        DEST_IMAGE="${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_DBT_IMAGE_NAME}:${_DBT_IMAGE_TAG}"
        docker pull "${_DBT_IMAGE_SOURCE}"
        docker tag "${_DBT_IMAGE_SOURCE}" "$${DEST_IMAGE}"
        docker push "$${DEST_IMAGE}"

  - name: hashicorp/terraform:1.6.6
    id: terraform-plan
    dir: infra
    entrypoint: sh
    args:
      - -c
      - terraform plan -var="project_id=${PROJECT_ID}" -var="dbt_image=${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_DBT_IMAGE_NAME}:${_DBT_IMAGE_TAG}" -out=tfplan

  - name: hashicorp/terraform:1.6.6
    id: terraform-apply-main-only
    dir: infra
    entrypoint: sh
    args:
      - -c
      - |
        if [ "${BRANCH_NAME}" = "master" ]; then
          echo "Main branch detected -> terraform apply"
          terraform apply -auto-approve tfplan
        else
          echo "Branch ${BRANCH_NAME} detected -> skipping terraform apply"
        fi

substitutions:
  _TF_STATE_BUCKET: retail-etl-tfstate
  _TF_STATE_PREFIX: terraform/infra
  _AR_REGION: europe-west1
  _AR_REPO: dbt-images
  _DBT_IMAGE_NAME: dbt-bigquery
  _DBT_IMAGE_TAG: 1.8.2
  _DBT_IMAGE_SOURCE: ghcr.io/dbt-labs/dbt-bigquery:1.8.2

options:
  logging: CLOUD_LOGGING_ONLY
